[package]
name = "deobf"
version = "0.5.1"
edition = "2021"
description = "Windows software protection and authenticated packaging toolkit"
license = "MIT"

[dependencies]
anyhow = "1"
argon2 = "0.5"
blake3 = "1"
chacha20poly1305 = "0.10"
clap = { version = "4", features = ["derive"] }
rand = "0.8"
rpassword = "7"
serde = { version = "1", features = ["derive"] }
zstd = "0.13"
zeroize = "1"
iced = { version = "0.13", default-features = false, features = ["tiny-skia", "fira-sans", "image", "lazy"] }
rfd = "0.15"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_System_Diagnostics_Debug"] }

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
incremental = false
strip = "symbols"
panic = "abort"
