pub mod analyzer;
pub mod artifact;
pub mod backends;
pub mod compatible;
pub mod container;
pub mod engine;
pub mod formats;
pub mod integrity;
pub mod limits;
pub mod loader;
pub mod manifest;
pub mod passes;
pub mod pipeline;
pub mod profile;
pub mod runtime;
pub mod validation;

pub use analyzer::{analyze, Analysis, Architecture};
pub use artifact::{ArtifactInfo, ArtifactKind};
pub use backends::{backend_for, protect_with_backend, BackendKind, BackendReport, ProtectionBackend};
pub use compatible::{protect_compatible, verify_compatible, CompatibilityManifest};
pub use container::{pack, unpack, ContainerInfo};
pub use engine::{analyze_only, kind_name, protect, protect_file, unprotect_file, AnalysisJson, EngineOptions, EngineResult};
pub use formats::{parse_pe, zip_has_manifest, BinaryFormat, PeInfo};
pub use limits::ResourceLimits;
pub use loader::{detect_restored, launch_python, launch_restored, restore_and_detect, LoaderPolicy};
pub use manifest::ProtectionManifest;
pub use passes::{CapabilityGuard, IntegrityGuard, SizeInvariant};
pub use pipeline::{Pass, Pipeline};
pub use profile::{ProtectionProfile, Strength};
pub use runtime::{default_runtime_output, run_protected, RuntimeKind};
pub use validation::{validate, ValidationReport};
