pub mod analyzer;
pub mod artifact;
pub mod container;
pub mod formats;
pub mod integrity;
pub mod limits;
pub mod manifest;
pub mod passes;
pub mod pipeline;
pub mod profile;
pub mod validation;

pub use analyzer::{analyze, Analysis, Architecture};
pub use artifact::ArtifactInfo;
pub use container::{pack, unpack, ContainerInfo};
pub use formats::{parse_pe, zip_has_manifest, BinaryFormat, PeInfo};
pub use limits::ResourceLimits;
pub use manifest::{ArtifactKind, ProtectionManifest};
pub use passes::{IntegrityGuard, SizeInvariant};
pub use pipeline::{Pass, Pipeline};
pub use profile::{ProtectionProfile, Strength};
pub use validation::{validate, ValidationReport};
