pub mod core;

pub use crate::core::{
    analyze,
    analyze_only,
    default_protected_output,
    default_runtime_output,
    protect,
    protect_compatible,
    protect_file,
    run_embedded_stub,
    run_protected,
    unprotect_bytes,
    unprotect_file,
    verify_compatible,
    Analysis,
    AnalysisJson,
    Architecture,
    ArtifactInfo,
    ArtifactKind,
    CompatibilityManifest,
    ContainerInfo,
    EngineOptions,
    EngineResult,
    Pass,
    Pipeline,
    ProtectionManifest,
    ProtectionProfile,
    ResourceLimits,
    RuntimeKind,
    Strength,
};
